server:
  port: 8001
spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://119.23.38.176/ims?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
          username: root
          password: qwer
          max-active: 20
          max-wait: 6000
          min-idel: 1
          test-on-borrow: true
          test-on-return: true
mybatis:
   mapperLocations: classpath*:/mapper/*Mapper.xml
   config-location: classpath:mybaties-config.xml
